alias ..='cd ..'
alias cd..='cd ..'
alias cdl='cd /usr/local/'
alias l='ls -l'
alias dir='dir --color=auto'
alias ld='ls -Al | grep ^d'
alias lf='ls -Al | grep ^-'
alias ls-l='ls -l'
alias md='mkdir -p'
alias vi='vim'
alias LC='LANG=C'
alias cls='clear'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias pstree='pstree -anpuh'
alias dpa='docker ps -a '
alias dia='docker images -a '
alias dp='docker ps '
alias di='docker images '
alias ds='docker search '
alias d='docker '
alias dv='docker  version'
alias hostname-s='/opt/dendyops/components/utils/set_hostname.sh '
alias install_nginx='/opt/dendyops/components/nginx/install_nginx.sh'
alias install_none='/opt/dendyops/components/nodejs/install_nodejs_npm.sh'
alias use_hw_yum_repo='/opt/dendyops/components/yum/use_huawei_yum_repo.sh'
alias docker-compose='docker compose '